---
abstract: 'Predicates for relationship accessors'
author:
  - 'Wallace Reis <wreis@cpan.org>'
build_requires:
  DBD::SQLite: 0
  Path::Class: 0
  SQL::Translator: 0.11006
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Relationship-Predicate
requires:
  DBIx::Class: 0
  Sub::Name: 0
  parent: 0
resources:
  bugtracker: https://github.com/wreis/DBIC-Relationship-Predicate/issues
  homepage: https://github.com/wreis/DBIC-Relationship-Predicate
  repository: git://github.com/wreis/DBIC-Relationship-Predicate.git
version: 0.04
